package net.loudcats.wyatt.skidgen;

import net.loudcats.wyatt.skidgen.modernworldgen.CavesAndCliffsWorldType;
import net.minecraft.util.EnumChatFormatting;
import net.minecraft.world.WorldType;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;

import static net.loudcats.wyatt.skidgen.SkidGen.MODID;

@Mod(
    modid = MODID,
    name = StringStorage.modName,
    version = StringStorage.verNum
    //guiFactory = Reference.GUI_FACTORY
)public class SkidGen {

    public static final String MODID = "skidgen";
    public static WorldType modernWorldGen;
    public static final Logger LOG = LogManager.getLogger(MODID);

    @SidedProxy(clientSide = "net.loudcats.wyatt.skidgen.ClientProxy", serverSide = "net.loudcats.wyatt.skidgen.CommonProxy")
    public static CommonProxy proxy;

    @Mod.EventHandler
    // preInit "Run before anything else. Read your config, create blocks, items, etc, and register them with the
    // GameRegistry." (Remove if not needed)
    public void preInit(FMLPreInitializationEvent event) {
        proxy.preInit(event);
        event.getModMetadata().autogenerated = false; // stops it from complaining about missing mcmod.info
        event.getModMetadata().logoFile = "assets/skidgen/skidgen_logo.png";
        event.getModMetadata().name = EnumChatFormatting.GOLD + "Skid"+ EnumChatFormatting.GREEN  + "Gen";
        event.getModMetadata().version = EnumChatFormatting.YELLOW + StringStorage.verNum;
        event.getModMetadata().credits = EnumChatFormatting.BLUE + "Original by" +EnumChatFormatting.AQUA + " neo-engineers " + EnumChatFormatting.BLUE + "Special thanks to" +EnumChatFormatting.AQUA + " AstroTibs " + EnumChatFormatting.BLUE + "for VillageNames' mod info thingy" ;
        event.getModMetadata().authorList.clear();
        event.getModMetadata().authorList.add(EnumChatFormatting.GOLD + ""+EnumChatFormatting.BOLD+ "WyattTheSkid");
        event.getModMetadata().url = EnumChatFormatting.GRAY + StringStorage.curseUrl;
        event.getModMetadata().description = EnumChatFormatting.GREEN + "1.18 Style world generation and world type based on GregGen for Minecraft 1.7.10";

    }

    @Mod.EventHandler
    // load "Do your mod setup. Build whatever data structures you care about. Register recipes." (Remove if not needed)
    public void init(FMLInitializationEvent event) {

        proxy.init(event);
        modernWorldGen = new CavesAndCliffsWorldType();
    }

    @Mod.EventHandler
    // postInit "Handle interaction with other mods, complete your setup based on this." (Remove if not needed)
    public void postInit(FMLPostInitializationEvent event) {
        proxy.postInit(event);
    }

    @Mod.EventHandler
    // register server commands in this event handler (Remove if not needed)
    public void serverStarting(FMLServerStartingEvent event) {
        proxy.serverStarting(event);
    }
}
